project:
  type: book
  output-dir: docs

book:
  title: "Elementary Statistics with R: STAT 2670"
  # author: "Yi Wang"
  # date: "9/5/2023"
  downloads: [pdf, docx]
  chapters:
    - index.qmd
    - intro.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.Rmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch10.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
urlcolor: blue
format:
  html:
    theme: cosmo
    code-fold: true
    html-math-method: katex
  pdf:
    documentclass: scrreprt
    geometry:
      - top=30mm
      - left=30mm
  docx:
    reference-doc: custom-reference-doc.docx



