---
author: "Yi Wang"
---

# SETTING-UP COMPUTING ENVIRONMENT {.unnumbered}

## Setting up your own computing environment on a personal computer

This is the recommended way and the advantage is that it's easy to handle files.

-   Go to the website <https://posit.co/download/rstudio-desktop/>.
-   Follow the two steps: 
    1) download and install R: Choose the appropriate operating system, and then choose "base" to "install R for the first time". You can simply accept all default options.  

    2)  download Rstudio Desktop and Install it.

After installation, start R-Studio, and you are ready to use it.

## Use R-Studio Cloud (No setting-up needed)

Alternatively, one can save the hassle of setting up on a personal computer and use the R-Studio Cloud for **free**. Here are the steps:

-   Go to the website <https://login.rstudio.cloud/>.

-   Either create a new account using an email address such as your AUM email or simply "Log in using Google" or click on other log-in alternative.

After log-in to your account, you are ready to use R Studio.

